export type ModType = "base" | "addon" | "kingdom";
export type ModStatus = "active" | "scaffold" | "concept";
export type Branch = "eastern" | "western" | "southern";

export interface Mod {
  name: string;
  shortName: string;
  type: ModType;
  status: ModStatus;
  prefix: string;
  folder: string;
  version: string;
  cover?: string;
  branch?: Branch;
  dlc?: string;
  cultures?: string[];
  ck3Title?: string;
  events?: number;
  decisions?: number;
  modifiers?: number;
  steamUrl?: string;
  repoUrl?: string;
  description: string;
}

export const TYPE_CONFIG: Record<ModType, { label: string; color: string; icon: string }> = {
  base:    { label: "Mod bazowy",  color: "#c5a048", icon: "⭐" },
  addon:   { label: "Addon",      color: "#e63946", icon: "⚡" },
  kingdom: { label: "Krolestwo",   color: "#83c84d", icon: "👑" },
};

export const STATUS_CONFIG: Record<ModStatus, { label: string; color: string }> = {
  active:   { label: "Aktywny rozwoj", color: "#83c84d" },
  scaffold: { label: "Scaffold",       color: "#e6b43c" },
  concept:  { label: "Koncepcja",      color: "#6ba0d6" },
};

export const BRANCH_CONFIG: Record<Branch, { label: string; color: string }> = {
  eastern:  { label: "Wschodnioslowianskie", color: "#e63946" },
  western:  { label: "Zachodnioslowianskie", color: "#6ba0d6" },
  southern: { label: "Poludniowoslowianskie", color: "#83c84d" },
};

export const MODS: Mod[] = [
  {
    name: "Slavic Enlarged",
    shortName: "SE",
    type: "base",
    status: "active",
    prefix: "se_",
    folder: "Slavic-Enlarged",
    version: "1.0.1",
    cover: "/marketing/se-cover.png",
    description: "35 kultur, 4 galeze wiary, 15 holy sites, system reformacji — kompletny overhaul Slowian w CK3.",
    steamUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=3740630117",
    repoUrl: "https://github.com/EntoGames/Slavic-Enlarged",
  },
  {
    name: "Slavic Struggle of Perun",
    shortName: "SSP",
    type: "addon",
    status: "active",
    prefix: "sessp_",
    folder: "Slavic Enlarged - Slavic Struggle of Perun",
    version: "1.0.0",
    cover: "/marketing/ssp-cover-v3.png",
    dlc: "Fate of Iberia",
    description: "Struggle System dla Slowian — fazy Swarozyc, Storm, Harmony, Veles, Marzanna. Catalysty, pivoty, endings.",
    repoUrl: "https://github.com/EntoGames/Slavic-Enlarged-Slavic-Struggle-of-Perun",
  },
  {
    name: "Myths & Legends",
    shortName: "SML",
    type: "addon",
    status: "concept",
    prefix: "sml_",
    folder: "Slavic Enlarged - Myths and Legends",
    version: "1.0.0",
    cover: "/marketing/sml-cover-v2.png",
    dlc: "Legends of the Dead",
    description: "System Legend dla Slowian — artefakty, legendy, mitologia. Faza koncepcyjna.",
  },
  {
    name: "Ruthenia Ancient Heartland",
    shortName: "Ruthenia",
    type: "kingdom",
    status: "active",
    prefix: "sekr_",
    folder: "Slavic Enlarged Ruthenia Ancient Heartland",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_ruthenia",
    cultures: ["polyans", "ulichs", "vyatichi", "severian"],
    events: 1, decisions: 0, modifiers: 3,
    description: "Kijow, Czernihow, Riazań — serce Rusi.",
  },
  {
    name: "White Ruthenia Forest Tribes",
    shortName: "White Ruthenia",
    type: "kingdom",
    status: "active",
    prefix: "sewr_",
    folder: "Slavic Enlarged White Ruthenia Forest Tribes",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_white_rus",
    cultures: ["dregovichs", "radimichs", "krivichians"],
    events: 4, decisions: 1, modifiers: 10,
    description: "Turow, Pinsk, Minsk, Smolensk — lesne plemiona.",
  },
  {
    name: "Novgorod Northern Republic",
    shortName: "Novgorod",
    type: "kingdom",
    status: "active",
    prefix: "senv_",
    folder: "Slavic Enlarged Novgorod Northern Republic",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_novgorod",
    cultures: ["krivichians", "ilmenian"],
    events: 3, decisions: 1, modifiers: 5,
    description: "Nowgorod, Psków — polnocna republika.",
  },
  {
    name: "Galicia-Volhynia Western Borderlands",
    shortName: "Galicia-Volhynia",
    type: "kingdom",
    status: "scaffold",
    prefix: "segv_",
    folder: "Slavic Enlarged Galicia-Volhynia Western Borderlands",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_galicia_volhynia",
    cultures: ["volhynian"],
    description: "Wolyń, Halicz, Grody Czerwienskie — zachodnie pogranicze Rusi.",
  },
  {
    name: "Moldavia River Frontier",
    shortName: "Moldavia",
    type: "kingdom",
    status: "scaffold",
    prefix: "semd_",
    folder: "Slavic Enlarged Moldavia River Frontier",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_moldavia",
    cultures: ["tivertsi"],
    description: "Bukowina, Moldawia, Budziak — granica nad rzekami.",
  },
  {
    name: "Polotsk Northern Gateway",
    shortName: "Polotsk",
    type: "kingdom",
    status: "scaffold",
    prefix: "sept_",
    folder: "Slavic Enlarged Polotsk Northern Gateway",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_white_rus",
    cultures: ["polochans"],
    description: "Polock — polnocna brama miedzy Rusią a Baltykiem.",
  },
  {
    name: "Opolye Eastern Steppe",
    shortName: "Opolye",
    type: "kingdom",
    status: "scaffold",
    prefix: "seop_",
    folder: "Slavic Enlarged Opolye Eastern Steppe",
    version: "1.0.0",
    branch: "eastern",
    ck3Title: "k_opolye",
    cultures: ["vyatichi"],
    description: "Wschodnie stepy — pogranicze ze stepem.",
  },
  {
    name: "Poland Piast Origins",
    shortName: "Poland",
    type: "kingdom",
    status: "active",
    prefix: "sepl_",
    folder: "Slavic Enlarged Poland Piast Origins",
    version: "1.0.0",
    branch: "western",
    ck3Title: "k_poland",
    cultures: ["polans", "goplans", "mazovians", "vistulan", "silesian"],
    events: 4, decisions: 1, modifiers: 6,
    description: "Wielkopolska, Kujawy, Mazowsze, Krakow, Slask — poczatki Piastow.",
  },
  {
    name: "Pomerania Baltic Shores",
    shortName: "Pomerania",
    type: "kingdom",
    status: "active",
    prefix: "sepm_",
    folder: "Slavic Enlarged Pomerania Baltic Shores",
    version: "1.0.0",
    branch: "western",
    ck3Title: "k_pomerania",
    cultures: ["kashubians", "lutici", "rani", "obodrites"],
    events: 6, decisions: 2, modifiers: 13,
    description: "Pomorze, Rugia, Meklemburgia — baltyckie wybrzeza.",
  },
  {
    name: "Sorbia Polabian Tribes",
    shortName: "Sorbia",
    type: "kingdom",
    status: "active",
    prefix: "sesb_",
    folder: "Slavic Enlarged Sorbia Polabian Tribes",
    version: "1.0.0",
    branch: "western",
    ck3Title: "k_sorbia",
    cultures: ["wagrians", "hevelli", "drevani", "sorbian"],
    events: 2, decisions: 0, modifiers: 4,
    description: "Holsztyn, Hawelandia, Wendland, Miśnia, Łużyce — plemiona polabskie.",
  },
  {
    name: "Bohemia Premyslid Legacy",
    shortName: "Bohemia",
    type: "kingdom",
    status: "scaffold",
    prefix: "sebh_",
    folder: "Slavic Enlarged Bohemia Premyslid Legacy",
    version: "1.0.0",
    cover: "/marketing/bohemia-cover.png",
    branch: "western",
    ck3Title: "k_bohemia",
    cultures: ["czech", "moravian"],
    description: "Czechy i Morawy — dziedzictwo Przemyslidow.",
  },
  {
    name: "Slovakia Born of Nitra",
    shortName: "Slovakia",
    type: "kingdom",
    status: "scaffold",
    prefix: "sesk_",
    folder: "Slavic Enlarged Slovakia Born of Nitra",
    version: "1.0.0",
    cover: "/marketing/slovakia-cover.png",
    branch: "western",
    ck3Title: "k_hungary",
    cultures: ["nitrianians"],
    description: "Nitra — ksiestwo slowackie pod korona wegierska.",
  },
  {
    name: "Hungary Slavic Enclaves",
    shortName: "Hungary",
    type: "kingdom",
    status: "scaffold",
    prefix: "sehg_",
    folder: "Slavic Enlarged Hungary Slavic Enclaves",
    version: "1.0.0",
    branch: "western",
    ck3Title: "k_hungary",
    cultures: ["nitrianians", "pannonian_slavs"],
    description: "Nitra, Blatnograd — slowianskie enklawy na Wegrzech.",
  },
  {
    name: "Carinthia Alpine Slavs",
    shortName: "Carinthia",
    type: "kingdom",
    status: "scaffold",
    prefix: "seca_",
    folder: "Slavic Enlarged Carinthia Alpine Slavs",
    version: "1.0.0",
    branch: "western",
    ck3Title: "k_carinthia",
    cultures: ["carantanian"],
    description: "Karyntia, Slowenia — alpejscy Slowianie.",
  },
  {
    name: "Croatia Adriatic Coast",
    shortName: "Croatia",
    type: "kingdom",
    status: "active",
    prefix: "secr_",
    folder: "Slavic Enlarged Croatia Adriatic Coast",
    version: "1.0.0",
    branch: "southern",
    ck3Title: "k_croatia",
    cultures: ["croatian"],
    events: 1, decisions: 0, modifiers: 1,
    description: "Dalmacja, wybrzeze adriatyckie — chorwackie krolestwo.",
  },
  {
    name: "Serbia Balkan Clans",
    shortName: "Serbia",
    type: "kingdom",
    status: "active",
    prefix: "serb_",
    folder: "Slavic Enlarged Serbia Balkan Clans",
    version: "1.0.0",
    branch: "southern",
    ck3Title: "k_serbia",
    cultures: ["serbian", "travunians", "docleani", "timocani", "branicevci"],
    events: 0, decisions: 0, modifiers: 3,
    description: "Raszka, Duklja, Braniczewo — balkanskie klany.",
  },
  {
    name: "Bulgaria Rhodope Highlands",
    shortName: "Bulgaria",
    type: "kingdom",
    status: "active",
    prefix: "sebg_",
    folder: "Slavic Enlarged Bulgaria Rhodope Highlands",
    version: "1.0.0",
    branch: "southern",
    ck3Title: "k_bulgaria",
    cultures: ["smolyani", "draguvites"],
    events: 1, decisions: 0, modifiers: 1,
    description: "Rodopy, Macedonia — wyzyny rodopskie.",
  },
];

export const modSlug = (m: Mod) => m.prefix.replace(/_$/, "");
