/* ───── Roadmap data for kingdom mods ───── */

export type VersionStatus = "done" | "current" | "planned" | "post";
export type PhaseType = "foundation" | "narrative" | "rivalry" | "territory" | "qa" | "release" | "post-release";

export interface RoadmapVersion {
  version: string;
  title: string;
  status: VersionStatus;
  phase: PhaseType;
  items: string[];
  decision?: string;
}

export interface RoadmapDecision {
  topic: string;
  decision: string;
  reason: string;
}

export interface KingdomRoadmap {
  preReleaseCount: number;
  postReleaseCount: number;
  releaseStats: { events: number; decisions: number; buildings: number; modifiers: number };
  versions: RoadmapVersion[];
  decisions: RoadmapDecision[];
}

export const PHASE_CONFIG: Record<PhaseType, { label: string; color: string }> = {
  foundation:     { label: "Fundament",     color: "#6ba0d6" },
  narrative:      { label: "Narracja",      color: "#e6b43c" },
  rivalry:        { label: "Rywalizacja",   color: "#e63946" },
  territory:      { label: "Terytoria",     color: "#83c84d" },
  qa:             { label: "QA",            color: "#78909c" },
  release:        { label: "Release",       color: "#c5a048" },
  "post-release": { label: "Post-release",  color: "#b39ddb" },
};

export const STATUS_ICON: Record<VersionStatus, string> = {
  done: "✓",
  current: "→",
  planned: "○",
  post: "◇",
};

export const KINGDOM_ROADMAPS: Record<string, KingdomRoadmap> = {
  /* ───── Bohemia ───── */
  "sebh_": {
    preReleaseCount: 24,
    postReleaseCount: 6,
    releaseStats: { events: 14, decisions: 6, buildings: 7, modifiers: 8 },
    versions: [
      { version: "0.1.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "scripted triggers", "loc framework"] },
      { version: "0.2.0", title: "Modyfikatory + HRE", status: "planned", phase: "foundation", items: ["8 modifierow", "sebh_imperial_vassal"], decision: "HRE modifier w 0.2.0" },
      { version: "0.3.0", title: "Trait Premyslida", status: "planned", phase: "foundation", items: ["sebh_trait_premyslid_legacy"] },
      { version: "0.4.0", title: "Decyzja: Koronacja w Pradze", status: "planned", phase: "foundation", items: ["sebh_dec_coronation"] },
      { version: "0.5.0", title: "Budynek: Vysehrad", status: "planned", phase: "foundation", items: ["Vysehrad modifier dynastyczny"], decision: "Vysehrad = modifier, NIE holy site" },
      { version: "0.6.0", title: "Court Position: Kapelan Praski", status: "planned", phase: "foundation", items: ["sebh_court_chaplain"] },
      { version: "0.7.0", title: "Chrzest Borivoja", status: "planned", phase: "narrative", items: ["Date trigger ~883", "konwersja + opor poganski"], decision: "Date trigger, nie on_faith_change" },
      { version: "0.8.0", title: "Smierc sw. Waclawa", status: "planned", phase: "narrative", items: ["Perspektywa Boleslawa", "fork: zabij/oszczedz"], decision: "Perspektywa Boleslawa (zabojcy)" },
      { version: "0.9.0", title: "Biskupstwo Praskie", status: "planned", phase: "narrative", items: ["973 event", "budynek katedra"] },
      { version: "0.10.0", title: "Slavnikovci: sojusz/eliminacja", status: "planned", phase: "rivalry", items: ["Fork: sojusz (flavor) vs eliminacja 995"], decision: "Sojusz = flavor only (vanilla dates nietykane)" },
      { version: "0.11.0", title: "Vrsovci: tolerancja/rzez", status: "planned", phase: "rivalry", items: ["Fork: toleruj vs rzez 1108"], decision: "Tolerancja ratuje niektorych (title overwrite)" },
      { version: "0.12.0", title: "Depoltici", status: "planned", phase: "rivalry", items: ["Event chain sukcesji", "title overwrite c_caslav"], decision: "Depoltici → c_caslav" },
      { version: "0.13.0", title: "Depoltici: Legnica 1241", status: "planned", phase: "rivalry", items: ["96028 ginie pod Legnica"] },
      { version: "0.14.0", title: "Vitkovci + Zavis", status: "planned", phase: "rivalry", items: ["Late-game event chain", "Zavis + Kunhuta + Vaclav II"] },
      { version: "0.15.0", title: "Decyzja: Sojusz lub eliminacja", status: "planned", phase: "rivalry", items: ["sebh_dec_slavnikovec_fate"] },
      { version: "0.16.0", title: "Apanaze morawskie", status: "planned", phase: "territory", items: ["Auto-detect on_title_gain", "Olomouc + Brno + Znojmo"], decision: "Apanaze = auto-detect, nie decyzja" },
      { version: "0.17.0", title: "Margrabistwo Moraw", status: "planned", phase: "territory", items: ["Nowy tytul d_margraviate_moravia"], decision: "Nowy tytul custom, nie modyfikacja vanilla" },
      { version: "0.18.0", title: "Decyzja: Dziedzic Welehradu", status: "planned", phase: "territory", items: ["sebh_dec_velehrad_heir"] },
      { version: "0.19.0", title: "Budynki: Kutna Hora + Sazava", status: "planned", phase: "territory", items: ["Kutna Hora → c_caslav", "Sazava → c_praha"], decision: "Baronie: KH→c_caslav, Saz→c_praha" },
      { version: "0.20.0", title: "Budynki: Spilberk + Olomouc", status: "planned", phase: "territory", items: ["Zamek margrabiow", "Biskupstwo"] },
      { version: "0.21.0", title: "Tenet: Dwoistosc koscielna", status: "planned", phase: "territory", items: ["Liturgia slowianska vs lacinska"] },
      { version: "0.22.0", title: "Mikulas Opavsky", status: "planned", phase: "territory", items: ["Bastard event chain", "uznanie/odrzucenie"] },
      { version: "0.23.0", title: "QA + balans", status: "planned", phase: "qa", items: ["Save-game", "balans", "SSP soft dep", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["Steam Workshop", "thumbnail", "CHANGELOG"] },
      { version: "1.1.0", title: "Cyryl i Metody (SE base)", status: "post", phase: "post-release", items: ["Hook w SE base event 863"], decision: "Event w SE base mod" },
      { version: "1.2.0", title: "Ostsiedlung", status: "post", phase: "post-release", items: ["Decyzja gracza: Zapros osadnikow"], decision: "Decyzja gracza, nie auto" },
      { version: "1.3.0", title: "Koronacja 1085", status: "post", phase: "post-release", items: ["Vratislav II pierwszy krol"] },
      { version: "1.4.0", title: "Budynek: Rotunda Znojmo", status: "post", phase: "post-release", items: ["Romanski unikat"] },
      { version: "1.5.0", title: "Legnica (niezalezne)", status: "post", phase: "post-release", items: ["Perspektywa czeska, zero cross-mod dep"], decision: "Niezalezne eventy" },
      { version: "1.6.0", title: "Hroznatici", status: "post", phase: "post-release", items: ["Budynek klasztorny w Teplej"], decision: "Post-release 1.6.0" },
    ],
    decisions: [
      { topic: "Vysehrad", decision: "Modifier dynastyczny", reason: "Nie holy site — prostsze, niezalezne od SSP" },
      { topic: "Depoltici tytul", decision: "c_caslav", reason: "c_hradec historycznie Slavnikovci; c_caslav wolne w vanilla" },
      { topic: "Kutna Hora baronia", decision: "c_caslav", reason: "Geograficznie poprawne" },
      { topic: "Sazava baronia", decision: "c_praha", reason: "W orbicie praskiej (~40km)" },
      { topic: "Slavnikovci sojusz", decision: "Flavor only", reason: "Vanilla daty smierci nietykane" },
      { topic: "Vrsovci tolerancja", decision: "Ratuje niektorych", reason: "Title overwrite kilku ocalonych" },
      { topic: "Chrzest trigger", decision: "Date trigger ~883", reason: "Pewniejszy timing niz on_faith_change" },
      { topic: "Waclav fork", decision: "Perspektywa Boleslawa", reason: "Gracz decyduje jako zabojca" },
      { topic: "Margrabistwo", decision: "Nowy tytul custom", reason: "d_margraviate_moravia — bez kolizji" },
      { topic: "Cyryl/Metody", decision: "Event w SE base mod", reason: "Zero duplikacji, oba mody hookuja" },
      { topic: "Apanaze", decision: "Auto-detect (on_title_gain)", reason: "Transparentna mechanika" },
      { topic: "Libusze", decision: "→ SML (Myths & Legends)", reason: "Mitologia, nie historia" },
      { topic: "Ostsiedlung", decision: "Decyzja gracza", reason: "Pelna kontrola nad kolonizacja" },
      { topic: "Legnica", decision: "Niezalezne eventy", reason: "Zero cross-mod dependency" },
      { topic: "Hroznatici", decision: "Budynek w Teplej (1.6.0)", reason: "Post-release" },
      { topic: "HRE", decision: "Modifier w 0.2.0", reason: "sebh_imperial_vassal: +prestiz, -autonomia" },
    ],
  },

  /* ───── Poland ───── */
  "sepl_": {
    preReleaseCount: 13,
    postReleaseCount: 5,
    releaseStats: { events: 14, decisions: 3, buildings: 4, modifiers: 13 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["4 eventy", "1 decyzja", "7 modifierow"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix", "standalone fallbacks"], decision: "has_mod guard na kazdym sessp_*" },
      { version: "0.11.0", title: "Standalone triggers + effects", status: "planned", phase: "foundation", items: ["sepl_is_poland_region", "sepl_is_piast", "sepl_is_lechitic_culture"] },
      { version: "0.12.0", title: "Budynki: Gniezno + Wawel", status: "planned", phase: "foundation", items: ["Katedra w Gnieznie", "Wawel"], decision: "4 budynki w pre-release" },
      { version: "0.13.0", title: "Budynki: Plock + Sleza", status: "planned", phase: "foundation", items: ["Brama Trojlukowa", "Sleza — swieta gora"] },
      { version: "0.14.0", title: "Reakcja poganska 1034", status: "planned", phase: "narrative", items: ["Maslaw na Mazowszu", "modifier na d_mazovia"], decision: "Maslaw = modifier na duchy, nie tytul" },
      { version: "0.15.0", title: "Zabojstwo bp. Stanislawa (1079)", status: "planned", phase: "narrative", items: ["Fork: zabij/ugoda", "perspektywa Boleslawa Smialego"] },
      { version: "0.16.0", title: "Testament Krzywoustego (1138)", status: "planned", phase: "narrative", items: ["Podzial na dzielnice", "modifier fragmentacja"] },
      { version: "0.17.0", title: "Decyzja: Przywroc Jednosc", status: "planned", phase: "narrative", items: ["Reunite Poland (major decision)"] },
      { version: "0.18.0", title: "Zamach w Gasawie (1227)", status: "planned", phase: "rivalry", items: ["Smierc Leszka Bialego", "fork: zemsta/dyplomacja"] },
      { version: "0.19.0", title: "Bitwa pod Legnica (1241)", status: "planned", phase: "rivalry", items: ["Poland owns, Bohemia info event", "Henryk Pobozny ginie"], decision: "Poland owns Legnica; Bohemia dostaje info" },
      { version: "0.20.0", title: "Rywalizacja galezi Piastow", status: "planned", phase: "rivalry", items: ["piast_branch_rivalry modifier", "auto-detect seniorat"] },
      { version: "0.21.0", title: "Ostsiedlung slaski", status: "planned", phase: "territory", items: ["Decyzja: Zapros osadnikow", "+development -cultural acceptance"] },
      { version: "0.22.0", title: "QA + balans", status: "planned", phase: "qa", items: ["Save-game", "SSP integration", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~14 eventow", "3 decyzje", "4 budynki", "~13 modifierow"] },
      { version: "1.1.0", title: "Maslaw ALT-history", status: "post", phase: "post-release", items: ["Okno Restauracji", "Powrot do Bogow Ojcow"] },
      { version: "1.2.0", title: "Jadwiga Slaska + Trzebnica", status: "post", phase: "post-release", items: ["Kult swietych", "budynek klasztor"] },
      { version: "1.3.0", title: "Krzyzacy 1226", status: "post", phase: "post-release", items: ["Konrad Mazowiecki zaprasza Zakon"] },
      { version: "1.4.0", title: "Budynek: Ostrow Lednicki", status: "post", phase: "post-release", items: ["Palatium wczesnopiastowskie"] },
      { version: "1.5.0", title: "Mazowsze Azyl", status: "post", phase: "post-release", items: ["Post-Arkona wolchwowie", "Sojusz z Litwa"] },
    ],
    decisions: [
      { topic: "SSP decoupling", decision: "has_mod guard", reason: "Wrap kazdy sessp_* w has_mod check" },
      { topic: "Budynki pre-release", decision: "Gniezno + Wawel + Sleza + Plock (4)", reason: "Pelny zestaw" },
      { topic: "Mieszko II / anarchia", decision: "Perspektywa Mieszka II", reason: "Fork: abdykuj/walcz" },
      { topic: "Gall Anonim", decision: "Court event + modifier", reason: "+learning, +prestige (~1112-1116)" },
      { topic: "Maslaw", decision: "Modifier na duchy mazowieckie", reason: "Fork: stlum/pozwol" },
      { topic: "Legnica 1241", decision: "Poland owns, Bohemia info", reason: "Event w modzie Poland" },
    ],
  },

  /* ───── Pomerania ───── */
  "sepm_": {
    preReleaseCount: 12,
    postReleaseCount: 4,
    releaseStats: { events: 13, decisions: 3, buildings: 4, modifiers: 20 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc", status: "done", phase: "foundation", items: ["6 eventow", "2 decyzje", "13 modifierow", "loc EN+PL"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy na 6 eventach + 2 decyzjach", "descriptor fix"] },
      { version: "0.11.0", title: "Standalone effects", status: "planned", phase: "foundation", items: ["sepm_shift_faith_toward_slavic_effect", "catalyst fallbacks"] },
      { version: "0.12.0", title: "Triglav Oracle", status: "planned", phase: "narrative", items: ["3 opcje: wyrok wojenny / przepowiednia / ucisz kaplanow"] },
      { version: "0.13.0", title: "Odbuduj Trzy Swiatynie", status: "planned", phase: "narrative", items: ["Decision + Triglav cult modifier"] },
      { version: "0.14.0", title: "Otto von Bamberg chain", status: "planned", phase: "narrative", items: ["Misjonarz 1120–1130", "3 forki: negocjuj/bron/daj azyl"] },
      { version: "0.15.0", title: "Dual cult axis", status: "planned", phase: "narrative", items: ["Arkona + Triglav synergia modifier"] },
      { version: "0.16.0", title: "Triglav priest trait", status: "planned", phase: "narrative", items: ["+2 learning", "dostep do proroctw"] },
      { version: "0.17.0", title: "Lutici culture events", status: "planned", phase: "territory", items: ["Pamiec Retry", "Krew Zwiazku", "2–3 modifiery"] },
      { version: "0.18.0", title: "Wagrians culture events", status: "planned", phase: "territory", items: ["Brama Polnocy", "kontakt z Dunczykami"] },
      { version: "0.19.0", title: "Arkona 3-tier building", status: "planned", phase: "territory", items: ["Grod Swiatynny → Twierdza → Emporium"], decision: "3-tier upgrade chain" },
      { version: "0.20.0", title: "Triglav temple building", status: "planned", phase: "territory", items: ["Swiatynia Tryglawa w c_stettin"] },
      { version: "0.21.0", title: "QA + balans", status: "planned", phase: "qa", items: ["Save-game", "SSP integration", "standalone test"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~13 eventow", "3 decyzje", "4 budynki", "~20 modifierow"] },
      { version: "1.1.0", title: "Federation decision + Baltic Fleet", status: "post", phase: "post-release", items: ["sepm_decision_polabian_federation", "Baltic Fleet modifier"] },
      { version: "1.2.0", title: "Arkona Council + Otto at Sea", status: "post", phase: "post-release", items: ["Rada co 25 lat", "1124 ALT: flota blokuje"] },
      { version: "1.3.0", title: "Baltic Arc (cross-mod)", status: "post", phase: "post-release", items: ["Cross z Polotsk", "-20% missionary efficiency"] },
      { version: "1.4.0", title: "Federation ending", status: "post", phase: "post-release", items: ["150 lat federacji = ending", "Stanica + Zbiornik Wody"] },
    ],
    decisions: [
      { topic: "Scope pre-release", decision: "Triglav + Federation oba w 1.0.0", reason: "Pelniejszy produkt na Workshop" },
      { topic: "Arkona budynek", decision: "3-tier upgrade chain", reason: "Swiatynia → umocnienia → emporium" },
      { topic: "Federation ownership", decision: "Pomerania owns, Sorbia hooks", reason: "Federacja = feature Pomeranii" },
      { topic: "Empty cultures", decision: "Rani + Wolinianie w 1.0.0", reason: "Cultural events + modifiers w pre-release" },
    ],
  },

  /* ───── Sorbia ───── */
  "sesb_": {
    preReleaseCount: 11,
    postReleaseCount: 5,
    releaseStats: { events: 8, decisions: 1, buildings: 0, modifiers: 7 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc", status: "done", phase: "foundation", items: ["2 eventy", "4 modifiers (2 orphaned)", "loc EN+PL"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix"] },
      { version: "0.11.0", title: "Standalone triggers + effects", status: "planned", phase: "foundation", items: ["sesb_is_sorbia_region", "sesb_is_polabian_culture"] },
      { version: "0.12.0", title: "Aktywacja orphaned modifiers", status: "planned", phase: "foundation", items: ["Trwalosc Luzycka event", "Swiety Plomien Lucicow event"] },
      { version: "0.13.0", title: "Luzyckie Refugium modifier", status: "planned", phase: "narrative", items: ["+50% opor culture conversion", "auto-trigger teren lesny/bagienny"] },
      { version: "0.14.0", title: "Decyzja: Archiwum Wolchwow", status: "planned", phase: "narrative", items: ["Chron kulture w 1 prowincji", "wymaga wolchwa na dworze"], decision: "Feniks = decyzja gracza" },
      { version: "0.15.0", title: "Event: Misjonarz po luzycku", status: "planned", phase: "narrative", items: ["Fork: zgoda (chroni kulture) / odrzuc (lacina)"] },
      { version: "0.16.0", title: "Trait: Ostatni Straznik", status: "planned", phase: "narrative", items: ["Jedyna prowincja sorbian = dynasty trait"] },
      { version: "0.17.0", title: "Event: Wiesniacy mowia po luzycku", status: "planned", phase: "narrative", items: ["Cykliczny co 15 lat", "3 opcje: asymiluj/pozwol/promuj"] },
      { version: "0.18.0", title: "Ending: Feniks Luzycki", status: "planned", phase: "narrative", items: [">=3 prowincje sorbian po 1150", "permanentny modifier"] },
      { version: "0.19.0", title: "Wagrians standalone event", status: "planned", phase: "territory", items: ["Flavor kupcy baltyccy", "dziala bez SSP"] },
      { version: "0.20.0", title: "QA + balans", status: "planned", phase: "qa", items: ["Save-game", "Refugium balans", "SSP integration"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["8 eventow", "1 decyzja", "7 modifierow", "1 trait"] },
      { version: "1.1.0", title: "Traktat Radogoski", status: "post", phase: "post-release", items: ["Konfederacja Polabska Srodkowa", "custom title"], decision: "Federation lite placeholder w 1.0 scope" },
      { version: "1.2.0", title: "Radogoszcz + Prawo Zwyczajowe", status: "post", phase: "post-release", items: ["+20 Fervor", "-30% missionary efficiency"] },
      { version: "1.3.0", title: "Schizma Polabska", status: "post", phase: "post-release", items: ["Swarozyc vs Swietowit", "fork 3 opcje"] },
      { version: "1.4.0", title: "Azyl Wolchwow (post-Arkona)", status: "post", phase: "post-release", items: ["Post-1168 event", "uciekinierzy z Arkony"] },
      { version: "1.5.0", title: "Ending: Radogoszcz Trwa", status: "post", phase: "post-release", items: ["Bufor Polabski", "Ostatni Ogien ending"] },
    ],
    decisions: [
      { topic: "Feniks mechanika", decision: "Decyzja 'Odrodzenie luzyckie'", reason: "Gracz kontroluje duchy + kultura sorbian" },
      { topic: "Scope 1.0.0", decision: "Feniks + Federation lite", reason: "1 decyzja Federation placeholder, eventy w post-release" },
      { topic: "Federation ownership", decision: "Sorbia hooks Pomerania", reason: "Federacja = feature Pomeranii via has_mod" },
    ],
  },

  /* ───── Slovakia ───── */
  "sesk_": {
    preReleaseCount: 13,
    postReleaseCount: 3,
    releaseStats: { events: 7, decisions: 3, buildings: 2, modifiers: 3 },
    versions: [
      { version: "0.1.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor fix", "SSP → soft dep", "scripted triggers + effects"] },
      { version: "0.2.0", title: "3 modyfikatory", status: "planned", phase: "foundation", items: ["great_moravian_heritage", "nitra_piety_center", "moravian_nitra_unification"] },
      { version: "0.3.0", title: "Decyzja: Koronacja w Nitrze", status: "planned", phase: "foundation", items: ["sesk_dec_coronation", "wymaga d_nyitra + slovien/nitrianians"] },
      { version: "0.4.0", title: "Pribina: przybycie + chrzest", status: "planned", phase: "narrative", items: ["NOWA postac Pribina (brak w vanilla)", "chrzest ~830"], decision: "Pribina = nowa postac CK3" },
      { version: "0.5.0", title: "Wygnanie przez Mojmira (833)", status: "planned", phase: "narrative", items: ["Fork: proba obrony / godne odejscie"], decision: "Perspektywa Nitry" },
      { version: "0.6.0", title: "Cyryl i Metody hook (863)", status: "planned", phase: "narrative", items: ["Hook w SE base mod event", "Slovakia-specific flavor"], decision: "Event w SE base mod" },
      { version: "0.7.0", title: "Szczyt Svatopluka (880)", status: "planned", phase: "narrative", items: ["Prestiz bonus", "modifier wzmacniajacy heritage"] },
      { version: "0.8.0", title: "Upadek Wielkich Moraw (907)", status: "planned", phase: "narrative", items: ["Death cluster hook 907.7.4", "3 smierci + tytul destroyed", "fork: heroiczna smierc / ucieczka"] },
      { version: "0.9.0", title: "Decyzja: Liturgia slowianska", status: "planned", phase: "territory", items: ["Fork: slowianska (+Slavic rulers) vs lacinska (+Pope)"] },
      { version: "0.10.0", title: "Decyzja: Odrodzenie Nitry", status: "planned", phase: "territory", items: ["Odtworzenie Ksiestwa Nitrzanskiego", "claim na k_moravia"] },
      { version: "0.11.0", title: "Bitwa pod Bratyslawa (907)", status: "planned", phase: "territory", items: ["Hook + event chain", "przygotowanie → bitwa → aftermath"], decision: "Hook w vanilla death cluster + event chain" },
      { version: "0.12.0", title: "Budynki: Kremnica + Bazylika", status: "planned", phase: "territory", items: ["Kopalnie Kremnicy (+30% tax)", "Bazylika w Nitrze (+piety)"] },
      { version: "0.13.0", title: "QA + balans", status: "planned", phase: "qa", items: ["Save-game", "SSP soft dep", "vanilla hookability check"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["7 eventow", "3 decyzje", "2 budynki", "3 modifiery"] },
      { version: "1.1.0", title: "Zjednoczenie Morawsko-Nitrzanskie", status: "post", phase: "post-release", items: ["Odtworzenie k_moravia", "cross z Bohemia"] },
      { version: "1.2.0", title: "Interakcja z Arpadovci", status: "post", phase: "post-release", items: ["Wegerskie podboje perspektywa Nitry", "fork: wasalstwo/opor"] },
      { version: "1.3.0", title: "Nitrianians culture expansion", status: "post", phase: "post-release", items: ["Tradycje kulturowe", "historyczne imiona"] },
    ],
    decisions: [
      { topic: "Perspektywa eventow", decision: "Perspektywa Nitry", reason: "Morawy jako zewnetrzna sila; pasuje do 'Born of Nitra'" },
      { topic: "Pribina", decision: "Nowa postac CK3", reason: "Brak w vanilla; holder c_nitra 830-833" },
      { topic: "Bratyslawa 907", decision: "Hook + event chain", reason: "Vanilla death cluster 907.7.4 hookable" },
      { topic: "Cyryl i Metody", decision: "Event w SE base mod", reason: "Slovakia hookuje; standard cross-mod" },
    ],
  },

  /* ───── Hungary ───── */
  "sehg_": {
    preReleaseCount: 16,
    postReleaseCount: 5,
    releaseStats: { events: 10, decisions: 2, buildings: 1, modifiers: 8 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor.mod fix", "standalone fallbacks"], decision: "has_mod guard; SE only dep" },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "sehg_is_hungary_slavic", "sehg_is_nitrianians", "sehg_is_pannonian_slavs", "sehg_has_ssp", "localization"] },
      { version: "0.12.0", title: "Modyfikatory religijne", status: "planned", phase: "foundation", items: ["sehg_old_gods_whisper", "sehg_slavic_revival_fervor", "sehg_latin_yoke", "sehg_pagan_undercurrent", "sehg_great_moravian_memory", "sehg_pannonian_crossroads"] },
      { version: "0.13.0", title: "Trait: Slowianski Konwertyta", status: "planned", phase: "foundation", items: ["sehg_slavic_convert (WROCIL do wiary)", "sehg_pagan_heart (ukryty sympaty)"] },
      { version: "0.14.0", title: "Decyzja: Powrot do Wiary Przodkow", status: "planned", phase: "foundation", items: ["sehg_dec_return_to_old_faith", "konwersja na se_slavic_west", "event chain 3 etapy", "Fervor +20"], decision: "Wiara docelowa: se_slavic_west; hybryda (decyzja + opcjonalny chain)" },
      { version: "0.15.0", title: "Decyzja: Azyl w Klasztorze", status: "planned", phase: "foundation", items: ["sehg_dec_monastery_asylum", "wolchwowie jako mnisi", "Fervor +5/rok"] },
      { version: "0.16.0", title: "Budynek: Stary Gaj", status: "planned", phase: "foundation", items: ["c_nitra", "+5 Fervor", "-25% missionary"], decision: "Lokacja: c_nitra (stolica Nitrianow)" },
      { version: "0.17.0", title: "Event chain: Glos Peruna", status: "planned", phase: "narrative", items: ["Sen o Starych Bogach", "Wolchw w Lesie", "Noc Kupaly — konwersja"] },
      { version: "0.18.0", title: "Event chain: Stefan Narzuca Lacine", status: "planned", phase: "narrative", items: ["1000 r.", "3 sciezki: Descent/Storm/Harmony"] },
      { version: "0.19.0", title: "Event: Pamiec Wielkich Moraw", status: "planned", phase: "narrative", items: ["prestige >= 500", "proklamacja lub zachowaj w sercu"] },
      { version: "0.20.0", title: "Event: Klasztor na Rozdrozu", status: "planned", phase: "rivalry", items: ["cykliczny co 12 lat", "opieraj sie / zaakceptuj / ochrona Madziara"] },
      { version: "0.21.0", title: "Event: Kaplan vs. Biskup", status: "planned", phase: "rivalry", items: ["spor jurysdykcji", "Harmony lub Descent"] },
      { version: "0.22.0", title: "Event: Madziarski Pan Przymyka Oko", status: "planned", phase: "rivalry", items: ["tolerancja", "Fervor +2/rok"] },
      { version: "0.23.0", title: "Modifier: Pod Madziarskim Butem", status: "planned", phase: "territory", items: ["narastajacy opor", "counter-intuitive mechanika"] },
      { version: "0.24.0", title: "Modifier: Enklawy Podziemne", status: "planned", phase: "territory", items: ["+5 Fervor/rok", "link do Dziady"] },
      { version: "0.25.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "loc audit", "SE + SSP kompatybilnosc"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~10 eventow", "2 decyzje", "1 budynek", "~8 modifierow"] },
      { version: "1.1.0", title: "Budynek: Klasztor Nitryjski", status: "post", phase: "post-release", items: ["c_nitra", "3-tier upgrade (chrzescijanski -> synkretyczny -> poganski)"] },
      { version: "1.2.0", title: "Decyzja: Proklamacja Restauracji Moraw", status: "post", phase: "post-release", items: ["konwersja + >=5 hrabstw -> claim na k_moravia"] },
      { version: "1.3.0", title: "Cross-mod: Cyryl i Metody", status: "post", phase: "post-release", items: ["Hook na SE base event 863"] },
      { version: "1.4.0", title: "Ending: Nitryjskie Odrodzenie", status: "post", phase: "post-release", items: [">=10 hrabstw wiara slowianska", "dynastia 100 lat", "Perun wrocil do Kotliny"] },
      { version: "1.5.0", title: "Event: Dziady nad Dunajem", status: "post", phase: "post-release", items: ["Hook na globalny event Dziadow", "lokalna wersja"] },
    ],
    decisions: [
      { topic: "Wiara docelowa", decision: "se_slavic_west", reason: "Zachodnislowianski odlam — najblizej Nitrianom kulturowo" },
      { topic: "Perspektywa konwersji", decision: "Hybryda", reason: "Decyzja natychmiastowa + opcjonalny event chain Glos Peruna" },
      { topic: "Pannonian Slavs", decision: "Wspolna sciezka", reason: "Obie kultury maja te sama decyzje konwersji — jednosc oporu" },
      { topic: "Sacred Grove lokacja", decision: "c_nitra", reason: "Stolica Nitrianow, siedziba Pribiny" },
    ],
  },

  /* ───── Carinthia ───── */
  "seca_": {
    preReleaseCount: 14,
    postReleaseCount: 4,
    releaseStats: { events: 5, decisions: 2, buildings: 1, modifiers: 4 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor.mod fix"], decision: "has_mod guard; SE only dep" },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "seca_is_carinthia", "seca_is_carantanian", "seca_has_ssp", "localization"] },
      { version: "0.12.0", title: "Modifier: Knezji Kamen", status: "planned", phase: "foundation", items: ["c_carinthia", "+5 Fervor", "+5% prestiz", "-20% missionary"] },
      { version: "0.13.0", title: "Modifier: Gorska Pamiec", status: "planned", phase: "foundation", items: ["terrain mountain", "-25% missionary", "wiara zmienia forme"] },
      { version: "0.14.0", title: "Event: Knezji Kamen czeka (per sukcesja)", status: "planned", phase: "foundation", items: ["on_title_gain (tylko dziedziczenie)", "3 opcje: slowianska/lacinska/obie"], decision: "Trigger: TYLKO dziedziczenie (nie podboj); opcja C = neutralna" },
      { version: "0.15.0", title: "Decyzja: Stroj Chlopa", status: "planned", phase: "foundation", items: ["po ceremonii slowianskiej (A/C)", "+15 opinion", "Harmony catalyst"] },
      { version: "0.16.0", title: "Budynek: Kamien Ksiazecy", status: "planned", phase: "foundation", items: ["c_carinthia", "+3 prestiz", "+2 Fervor", "-15% missionary"] },
      { version: "0.17.0", title: "Event: Frankijski Biskup Protestuje", status: "planned", phase: "narrative", items: ["po ceremonii slowianskiej", "poddaj sie / bron / ignoruj"] },
      { version: "0.18.0", title: "Event chain: Karantanskie Dwuwierstwo", status: "planned", phase: "narrative", items: ["synkretyzm", "balans Fervor vs. kosciol"] },
      { version: "0.19.0", title: "Event: Habsburgowie Zadaja Podatku", status: "planned", phase: "narrative", items: ["XIII w.", "plac / opor / hold symboliczny"] },
      { version: "0.20.0", title: "Decyzja: Model Karantanski", status: "planned", phase: "rivalry", items: ["eksport modelu do sasiadow", "prosta decyzja z modifier"], decision: "Pre-release — prosta wersja bez cross-mod hookow" },
      { version: "0.21.0", title: "Event: Etos Egalitarny", status: "planned", phase: "rivalry", items: ["rownosc stanow", "chlop i ksiaze rownoprawni"] },
      { version: "0.22.0", title: "Modifier: Dolina Alpejska", status: "planned", phase: "territory", items: ["izolacja gorska", "trwalosc wiary"] },
      { version: "0.23.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "on_title_gain triggery", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~5 eventow", "2 decyzje", "1 budynek", "~4 modifierow"] },
      { version: "1.1.0", title: "Ending: Karantanska Synteza", status: "post", phase: "post-release", items: [">=5 ceremonii + dynastia 150 lat + >=3 hrabstwa", "Knezji Kamen zyje"], decision: "Post-release (1.1.0) — w 1.0.0 ceremonia + fundament" },
      { version: "1.2.0", title: "Decyzja: Oglos Model Karantanski", status: "post", phase: "post-release", items: ["po Endingu Synteza", "eksport synkretyzmu"] },
      { version: "1.3.0", title: "Cross-mod: Syncretic Events", status: "post", phase: "post-release", items: ["Hook na Kupala, Dziady", "lokalne warianty alpejskie"] },
      { version: "1.4.0", title: "Event chain: Karantanskie Dziedzictwo", status: "post", phase: "post-release", items: ["late-game", "XIII-XIV w."] },
    ],
    decisions: [
      { topic: "Knezji Kamen trigger", decision: "Tylko dziedziczenie", reason: "Ceremonia to tradycja dynastyczna — podbojca nie ma prawa" },
      { topic: "Opcja C konsekwencje", decision: "Neutralna", reason: "Kompromis to krotki modifier, nie sciezka narracyjna" },
      { topic: "Ending Synteza", decision: "Post-release (1.1.0)", reason: "W 1.0.0 ceremonia + fundament; Ending po releaasie" },
      { topic: "Model Karantanski", decision: "Pre-release (prosty)", reason: "Prosta decyzja z modifier — bez cross-mod hookow" },
    ],
  },

  /* ───── Croatia ───── */
  "secr_": {
    preReleaseCount: 12,
    postReleaseCount: 4,
    releaseStats: { events: 8, decisions: 2, buildings: 1, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["1 event (secr_levelb.0055)", "loc EN+PL"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix", "standalone fallbacks"], decision: "has_mod guard; SE only dep" },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "secr_is_croatia_region", "secr_is_croatian_culture", "localization"] },
      { version: "0.12.0", title: "Modyfikatory", status: "planned", phase: "foundation", items: ["secr_glagolitic_shield", "secr_twelve_rods", "secr_adriatic_crossroads", "secr_vlastela_pride"] },
      { version: "0.13.0", title: "Rozbudowa Glagolickiej Tarczy", status: "planned", phase: "narrative", items: ["secr_levelb.0055 rozbudowa", "nowe triggery standalone", "fork: ochrona/kompromis"], decision: "Zachowaj + rozbuduj istniejacy event" },
      { version: "0.14.0", title: "Event chain: 12 Rodow Chorwackich", status: "planned", phase: "narrative", items: ["Pakt rodowy", "modifier jednosci", "flavor per duchy"] },
      { version: "0.15.0", title: "Decyzja: Plemenita Vlastela", status: "planned", phase: "narrative", items: ["Gracz aktywuje ochrone rodowa", "modifier +opinion +levy"], decision: "Decyzja gracza (nie globalny modifier)" },
      { version: "0.16.0", title: "Event: Sobor w Splicie (1060)", status: "planned", phase: "narrative", items: ["Date trigger 1060", "ograniczenie liturgii slowianskiej", "fork: podporzadkuj sie / bron / ukryj"], decision: "Date trigger 1060 (pewny timing historyczny)" },
      { version: "0.17.0", title: "Event: Tomislav Jednoczy", status: "planned", phase: "rivalry", items: ["Zjednoczenie Chorwacji", "prestige chain"] },
      { version: "0.18.0", title: "Budynek: Katedra w Ninie", status: "planned", phase: "territory", items: ["c_zadar lub c_spalato", "+piety", "+Fervor"] },
      { version: "0.19.0", title: "Modifier: Wenecja Napiera", status: "planned", phase: "territory", items: ["narastajacy wplyw Wenecji", "presja handlowa na wybrzezu"] },
      { version: "0.20.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "loc audit", "SSP kompatybilnosc"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~8 eventow", "2 decyzje", "1 budynek", "~6 modifierow"] },
      { version: "1.1.0", title: "Trpimir i Pacta Conventa", status: "post", phase: "post-release", items: ["Dynastia Trpimir", "pakt z wasalami"] },
      { version: "1.2.0", title: "Neretwianie piraccy", status: "post", phase: "post-release", items: ["Piractwo adriatyckie", "morskie raidy"] },
      { version: "1.3.0", title: "Cross-mod: Glagolica arc", status: "post", phase: "post-release", items: ["Hook na SE base Cyryl/Metody", "wzmocnienie tarczy"] },
      { version: "1.4.0", title: "Ending: Tarcza Glagolicka Trwa", status: "post", phase: "post-release", items: ["Liturgia slowianska przetrwala", "permanentny modifier"] },
    ],
    decisions: [
      { topic: "Event Glagolicka Tarcza", decision: "Zachowaj + rozbuduj", reason: "secr_levelb.0055 zostaje; nowe triggery standalone" },
      { topic: "Plemenita Vlastela", decision: "Decyzja gracza", reason: "Gracz aktywuje ochrone rodowa — wiecej kontroli" },
      { topic: "Sobor w Splicie", decision: "Date trigger 1060", reason: "Pewny timing historyczny jak Stefan w Hungary" },
    ],
  },

  /* ───── Serbia ───── */
  "serb_": {
    preReleaseCount: 15,
    postReleaseCount: 4,
    releaseStats: { events: 10, decisions: 2, buildings: 1, modifiers: 8 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["Placeholder flow — wymaga fix"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix", "standalone fallbacks"], decision: "has_mod guard; SE only dep" },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "serb_is_serbia_region", "serb_is_serbian", "serb_is_timocani", "serb_is_branicevci", "localization"] },
      { version: "0.12.0", title: "Placeholder fix", status: "planned", phase: "foundation", items: ["Eventy nadaja modifiery (15 lat duration)", "gracz musi odnawiac"], decision: "Modifiery 15 lat — powtarzalnosc eventow" },
      { version: "0.13.0", title: "Modyfikatory", status: "planned", phase: "foundation", items: ["serb_dual_orbit", "serb_byzantine_pull", "serb_western_pull", "serb_tribal_memory", "serb_zupan_pride"] },
      { version: "0.14.0", title: "Decyzja: Wybierz Orbite", status: "planned", phase: "foundation", items: ["Bizancjum vs Zachod", "modifier + opinion chain"] },
      { version: "0.15.0", title: "Event: Knez Wlastimir", status: "planned", phase: "narrative", items: ["Zjednoczenie Raszki", "founder prestige chain"] },
      { version: "0.16.0", title: "Event: Caslav Klonimirovic", status: "planned", phase: "narrative", items: ["Restauracja serbska ~927", "fork: kontynuuj / zmien kurs"] },
      { version: "0.17.0", title: "Event: Timocani/Branicevci", status: "planned", phase: "narrative", items: ["Wspolny event z flavor per kultura", "warianty: Timocani/Branicevci"], decision: "Wspolne eventy + flavor (1 event, per-culture variants)" },
      { version: "0.18.0", title: "Event: Stefan Nemanja (1166)", status: "planned", phase: "narrative", items: ["Zjednoczenie + chrzest", "Fundator dynastii Nemanjicow"] },
      { version: "0.19.0", title: "Event chain: Dual Orbit", status: "planned", phase: "rivalry", items: ["Cykliczny co 15 lat", "ciagniecie w strone Bizancjum/Zachodu"] },
      { version: "0.20.0", title: "Event: Zupan Zbuntowany", status: "planned", phase: "rivalry", items: ["Lokalni zupani", "fork: stlum/negocjuj/pozwol"] },
      { version: "0.21.0", title: "Budynek: Studenica", status: "planned", phase: "territory", items: ["Klasztor Studenica", "+piety +prestige"] },
      { version: "0.22.0", title: "Modifier: Gorska Raszka", status: "planned", phase: "territory", items: ["Izolacja gorna", "opor vs. imperium"] },
      { version: "0.23.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "dual orbit balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~10 eventow", "2 decyzje", "1 budynek", "~8 modifierow"] },
      { version: "1.1.0", title: "Sveti Sava + Autokefalia", status: "post", phase: "post-release", items: ["Serbska Cerkiew autokefaliczna", "piety chain"] },
      { version: "1.2.0", title: "Kosowo: Lazar i Brankowicze", status: "post", phase: "post-release", items: ["1389 event", "fork: honor/zdrada"] },
      { version: "1.3.0", title: "Cross-mod: Bogomilizm arc", status: "post", phase: "post-release", items: ["Hook na Bulgaria bogomilski", "serbski wariant"] },
      { version: "1.4.0", title: "Ending: Dwa Slonca", status: "post", phase: "post-release", items: ["Balans Bizancjum/Zachod utrzymany 150 lat", "permanentny modifier"] },
    ],
    decisions: [
      { topic: "Placeholder flow", decision: "Eventy nadaja modifiery (15 lat)", reason: "Gracz musi odnawiac — powtarzalnosc" },
      { topic: "Kultury Timocani/Branicevci", decision: "Wspolne eventy + flavor", reason: "Jeden event z wariantami per kultura — mniej kodu" },
    ],
  },

  /* ───── Bulgaria ───── */
  "segb_": {
    preReleaseCount: 12,
    postReleaseCount: 4,
    releaseStats: { events: 8, decisions: 2, buildings: 2, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix"], decision: "has_mod guard; SE only dep" },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "segb_is_bulgaria_region", "segb_is_bulgarian_culture", "localization"] },
      { version: "0.12.0", title: "Modyfikatory", status: "planned", phase: "foundation", items: ["segb_alt_893", "segb_vladimir_restoration", "segb_rhodope_pagan", "segb_preslav_glory"] },
      { version: "0.13.0", title: "Event: Smierc Borysa I (893)", status: "planned", phase: "narrative", items: ["ALT dywergencja", "Wladimir przywraca poganstwo", "fork: walcz/przyjmij/ucieknij"], decision: "ALT 893 = core 1.0.0 (rdzen moda)" },
      { version: "0.14.0", title: "Event chain: Wladimir vs Symeon", status: "planned", phase: "narrative", items: ["Rywalizacja braci", "3 ery: poganstwo → kompromis → rozstrzygniecie"] },
      { version: "0.15.0", title: "Decyzja: Restauracja Peruna", status: "planned", phase: "narrative", items: ["segb_dec_restore_perun", "konwersja prowincji + Fervor"] },
      { version: "0.16.0", title: "Event: Bogomilizm", status: "planned", phase: "narrative", items: ["Ruch bogomilski", "alternatywa dla chrzescijanstwa", "fork: toleruj/stlum/adoptuj"], decision: "Pre-release (0.16.0) — kluczowy dla narracji" },
      { version: "0.17.0", title: "Budynki: Swiatynia Peruna + Palac Wladimira", status: "planned", phase: "territory", items: ["c_preslav: Swiatynia (+Fervor +opinion)", "c_preslav: Palac (+prestige +tax)"], decision: "2 budynki — religijny + polityczny" },
      { version: "0.18.0", title: "Event: Rodopskie Uchranianie", status: "planned", phase: "territory", items: ["Gorska izolacja", "poganski azyl w Rodopach"] },
      { version: "0.19.0", title: "Modifier: Stara Wiara Balkanu", status: "planned", phase: "territory", items: ["-30% missionary", "+Fervor za terrain mountain"] },
      { version: "0.20.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "ALT 893 balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~8 eventow", "2 decyzje", "2 budynki", "~6 modifierow"] },
      { version: "1.1.0", title: "Samuel i Ohrydzki Patriarchat", status: "post", phase: "post-release", items: ["Imperium Samuela", "piety chain"] },
      { version: "1.2.0", title: "Cross-mod: Serbia bogomilski arc", status: "post", phase: "post-release", items: ["Hook na Serbia dual orbit", "bogomilski wariant"] },
      { version: "1.3.0", title: "Budynek: Twierdza Preslaw", status: "post", phase: "post-release", items: ["Obrona stolicy", "+fort_level +garrison"] },
      { version: "1.4.0", title: "Ending: Dywergencja 893", status: "post", phase: "post-release", items: ["Wladimir wygral", "Bulgaria poganska 150 lat", "permanentny modifier"] },
    ],
    decisions: [
      { topic: "ALT 893 scope", decision: "Core 1.0.0", reason: "Wladimir to rdzen moda — eventy 893+ w pre-release" },
      { topic: "Bogomilizm", decision: "Pre-release (0.16.0)", reason: "Kluczowy dla narracji poganskiej Bulgarii" },
      { topic: "Budynek Preslaw", decision: "2 budynki", reason: "Swiatynia Peruna (religia) + Palac Wladimira (polityka)" },
    ],
  },

  /* ───── Ruthenia ───── */
  "sekr_": {
    preReleaseCount: 14,
    postReleaseCount: 5,
    releaseStats: { events: 10, decisions: 2, buildings: 1, modifiers: 8 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["1 event (Drevlyans Tax Revolt)", "placeholder modifiers", "loc EN+PL"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix", "standalone fallbacks"], decision: "has_mod guard; SE only dep" },
      { version: "0.11.0", title: "Standalone triggers + effects", status: "planned", phase: "foundation", items: ["sekr_is_ruthenia_region", "sekr_is_vyatichi", "sekr_is_drevlyans", "sekr_is_severian"] },
      { version: "0.12.0", title: "Modyfikatory religijne", status: "planned", phase: "foundation", items: ["sekr_old_gods_whisper", "sekr_pagan_undercurrent", "sekr_perun_hill", "sekr_slavic_revival"] },
      { version: "0.13.0", title: "Event: Kodyfikacja Panteonu (ALT 988)", status: "planned", phase: "narrative", items: ["Vladimir formalizuje panteon", "7 bogow na wzgorzach Kijowa"], decision: "ALT 988 = core 1.0.0" },
      { version: "0.14.0", title: "Decyzja: Powrot do Wiary Przodkow", status: "planned", phase: "narrative", items: ["sekr_dec_pantheon_codification", "Fervor +20", "modifier permanentny"] },
      { version: "0.15.0", title: "Event chain: Wolchw Metropolia", status: "planned", phase: "narrative", items: ["Zapis mitow", "hierarchia kaplanska", "Fervor +5/rok"] },
      { version: "0.16.0", title: "Event: Neutralnosc Poganska", status: "planned", phase: "narrative", items: ["-50% missionary dla obu religii", "balans miedzy chrzescijanstwami"] },
      { version: "0.17.0", title: "Event: Drevlyans Bunt (rozbudowa)", status: "planned", phase: "rivalry", items: ["Rozbudowa istniejacego eventu", "nowe forki"] },
      { version: "0.18.0", title: "Event: Severian Sojusz Nomadow", status: "planned", phase: "rivalry", items: ["Aktywacja placeholder modifier", "sojusz z koczownikami"] },
      { version: "0.19.0", title: "Modifier: Poganski Latarnik", status: "planned", phase: "territory", items: ["+15 Fervor globalny gdy Rus poganska"] },
      { version: "0.20.0", title: "Budynek: Wzgorze Peruna", status: "planned", phase: "territory", items: ["c_chernigov", "+Fervor", "+prestige", "-missionary"], decision: "Lokacja: c_chernigov" },
      { version: "0.21.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "loc audit", "SSP kompatybilnosc"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~10 eventow", "2 decyzje", "1 budynek", "~8 modifierow"] },
      { version: "1.1.0", title: "Cyryl i Metody hook", status: "post", phase: "post-release", items: ["Hook na SE base event 863"] },
      { version: "1.2.0", title: "Cross-mod: Vyatichi arc", status: "post", phase: "post-release", items: ["Hook na Opolye seop_ (wspolna kultura)"] },
      { version: "1.3.0", title: "Budynek: Swiatynia na Peruni", status: "post", phase: "post-release", items: ["Druga swiatynia w regionie"] },
      { version: "1.4.0", title: "Event: Tatarski Wyslannnik (1240)", status: "post", phase: "post-release", items: ["Negocjacje poganska Rus + Mongolowie"], decision: "Post-release (late-game event)" },
      { version: "1.5.0", title: "Ending: Krolestwo Peruna", status: "post", phase: "post-release", items: ["Vladimir wygral", "Rus poganska 150 lat"] },
    ],
    decisions: [
      { topic: "ALT 988 scope", decision: "Core 1.0.0", reason: "Panteon Vladimira to rdzen moda" },
      { topic: "Budynek lokacja", decision: "c_chernigov", reason: "Drugie miasto Rusi, alternatywna stolica" },
      { topic: "Tatarski Wyslannnik", decision: "Post-release", reason: "1240 to pozny event; core to ALT 988" },
    ],
  },

  /* ───── White Ruthenia ───── */
  "sewr_": {
    preReleaseCount: 14,
    postReleaseCount: 4,
    releaseStats: { events: 10, decisions: 3, buildings: 0, modifiers: 8 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["4 eventy Krivichians", "1 event Dregovichs", "1 decision Cultural Bridge", "modifiers", "loc EN+PL"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix", "standalone fallbacks"] },
      { version: "0.11.0", title: "Standalone triggers", status: "planned", phase: "foundation", items: ["sewr_is_white_ruthenia", "sewr_is_krivichians", "sewr_is_dregovichs", "sewr_is_radimichs"] },
      { version: "0.12.0", title: "Modifier: Puszcza Polesie", status: "planned", phase: "foundation", items: ["-50% conversion resistance", "-10% development", "+10% levy"] },
      { version: "0.13.0", title: "Decyzja: Pakt z Puszcza", status: "planned", phase: "narrative", items: ["Dregovichs izolacja", "+conversion resistance", "-15% movement"] },
      { version: "0.14.0", title: "Event: Chrzciny na Szlaku", status: "planned", phase: "narrative", items: ["Co 12 lat: kupiec chce kaplice", "3 opcje"] },
      { version: "0.15.0", title: "Event: Zercy szukaja schronienia", status: "planned", phase: "narrative", items: ["Uchodccy kaplani z konwertowanych krolestw"] },
      { version: "0.16.0", title: "Modifier: Ostatnia Puszcza", status: "planned", phase: "narrative", items: ["Endgame modifier", "ostatni bastion poganski"] },
      { version: "0.17.0", title: "Modifier: Gleboki Las", status: "planned", phase: "narrative", items: ["-40% missionary", "stack z Home is Temple"] },
      { version: "0.18.0", title: "Event: Zaduszki Lesne", status: "planned", phase: "rivalry", items: ["Coroczne rytualy przodkow", "+7 Fervor"] },
      { version: "0.19.0", title: "Event: Mnich w Puszczy", status: "planned", phase: "rivalry", items: ["Samotny misjonarz", "3 opcje"] },
      { version: "0.20.0", title: "Decyzja: Zamkniecie Puszczy", status: "planned", phase: "territory", items: ["30 lat izolacji", "0% missionary", "-50% dev", "-40% income"], decision: "Decyzja gracza (nie auto-trigger)" },
      { version: "0.21.0", title: "Modifier: Lesny Wolchw", status: "planned", phase: "territory", items: ["Character modifier", "+10 Fervor lokalnie", "niewidzialny dla misjonarzy"], decision: "Pre-release" },
      { version: "0.22.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "forest balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~10 eventow", "3 decyzje", "0 budynkow", "~8 modifierow"] },
      { version: "1.1.0", title: "Cross-mod: Wolchw z Opolya", status: "post", phase: "post-release", items: ["Hook na seop_ refugee volkhv event"] },
      { version: "1.2.0", title: "Event: Weles Zwierzat", status: "post", phase: "post-release", items: ["Rytualy lowieckie", "+3 Fervor per ceremonia"] },
      { version: "1.3.0", title: "Decyzja: Osadnictwo w Puszczy", status: "post", phase: "post-release", items: ["Nowe lesne prowincje z Blessing"] },
      { version: "1.4.0", title: "Ending: Puszcza Niczyja", status: "post", phase: "post-release", items: ["Niezdobyta puszcza", "permanentny modifier"] },
    ],
    decisions: [
      { topic: "Zamkniecie Puszczy", decision: "Decyzja gracza", reason: "Pelna kontrola nad tradeoffem izolacji" },
      { topic: "Lesny Wolchw", decision: "Pre-release", reason: "Kluczowa mechanika lesnego ukrycia w 1.0.0" },
    ],
  },

  /* ───── Novgorod ───── */
  "senv_": {
    preReleaseCount: 14,
    postReleaseCount: 4,
    releaseStats: { events: 8, decisions: 2, buildings: 1, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc (migracja z SSP)", status: "done", phase: "foundation", items: ["3 eventy Ilmenian (Bell of Veche + voting)", "1 decision Convene Veche", "modifiers", "loc EN+PL"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix", "standalone fallbacks"] },
      { version: "0.11.0", title: "Standalone triggers", status: "planned", phase: "foundation", items: ["senv_is_novgorod_region", "senv_is_ilmenian", "senv_has_ssp"] },
      { version: "0.12.0", title: "Modyfikatory", status: "planned", phase: "foundation", items: ["senv_novogradska_wolnosc", "senv_varangian_route_hub"] },
      { version: "0.13.0", title: "Event: Wiec zada wygnania", status: "planned", phase: "narrative", items: ["Ikoniczna mechanika Nowgorodu", "3 opcje: ustap/stlum/negocjuj"] },
      { version: "0.14.0", title: "Modifier: Novogradska Wolnosc", status: "planned", phase: "narrative", items: ["+development", "+trade income", "-domain power"] },
      { version: "0.15.0", title: "Modifier: Broken Veche", status: "planned", phase: "narrative", items: ["-opinion 20 lat po stlumieniu"], decision: "Broken Veche 20 lat (reversible)" },
      { version: "0.16.0", title: "Integracja se_tradition_veche_rule", status: "planned", phase: "narrative", items: ["Opcja D 'Wiec reformuje prawo'"] },
      { version: "0.17.0", title: "Event: Liga Kupcow", status: "planned", phase: "rivalry", items: ["Proto-Hansa", "sojusz handlowy"] },
      { version: "0.18.0", title: "Event: Tatarzy omijaja Nowogrod (1240)", status: "planned", phase: "rivalry", items: ["Historyczny event", "bogowie chronili"] },
      { version: "0.19.0", title: "Budynek: Dwor Jaroslawa", status: "planned", phase: "territory", items: ["c_novgorod", "+trade", "+prestige"] },
      { version: "0.20.0", title: "Modifier: Varangian Route Hub", status: "planned", phase: "territory", items: ["Bonus handlowy za kontrole szlaku"] },
      { version: "0.21.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "veche balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~8 eventow", "2 decyzje", "1 budynek", "~6 modifierow"] },
      { version: "1.1.0", title: "ALT: Republika Welesianska (1136)", status: "post", phase: "post-release", items: ["Wiec odrzuca arcybiskupa", "kupiecka republika Welesa"] },
      { version: "1.2.0", title: "Court: Posadnik + Tysiacki", status: "post", phase: "post-release", items: ["Posadnik +15% trade", "Tysiacki +10% levy"], decision: "Court positions post-release" },
      { version: "1.3.0", title: "Cross-mod: Polotsk Varangian Route", status: "post", phase: "post-release", items: ["Hook na sept_ wspolny modifier"] },
      { version: "1.4.0", title: "Ending: Welesianska Republika", status: "post", phase: "post-release", items: ["Poganska republika handlowa do 1300"] },
    ],
    decisions: [
      { topic: "Tlumienie wiecu", decision: "Broken Veche (20 lat)", reason: "Reversible modifier, nie permanentny upadek" },
      { topic: "Court positions", decision: "Post-release", reason: "W 1.0.0 eventy + modifiery wystarczajace" },
    ],
  },

  /* ───── Galicia-Volhynia ───── */
  "segv_": {
    preReleaseCount: 12,
    postReleaseCount: 4,
    releaseStats: { events: 6, decisions: 1, buildings: 0, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix"] },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "segv_is_galicia_volhynia", "segv_is_volhynian", "localization"] },
      { version: "0.12.0", title: "Modifier: Boyar Power", status: "planned", phase: "foundation", items: ["+5 vassal opinion", "-5 authority opinion"] },
      { version: "0.13.0", title: "Modifier: Dual Frontier", status: "planned", phase: "foundation", items: ["-20% missionary gdy Latin + Orthodox sasiedzi"], decision: "Passive auto (geography is mechanic)" },
      { version: "0.14.0", title: "Event: Zjazd Moznych Halicza", status: "planned", phase: "narrative", items: ["Co 10 lat: bojarzy vs. ksiaze", "3 opcje"] },
      { version: "0.15.0", title: "Decyzja: Straz Pogranicza", status: "planned", phase: "narrative", items: ["Siec straznicza", "+defense", "-development"] },
      { version: "0.16.0", title: "Event: Dialog Wolchwy z Dwoch Stron", status: "planned", phase: "narrative", items: ["Polabscy i ruscy kaplani", "sojusz/schizma/synkretyzm"] },
      { version: "0.17.0", title: "Modifier: Dual Pressure", status: "planned", phase: "rivalry", items: ["-30% missionary dla obu religii"] },
      { version: "0.18.0", title: "Event: Tatarski Chaos (1240)", status: "planned", phase: "rivalry", items: ["Zniszczenie = powrot do wiary", "+Fervor"], decision: "On_action (reaguje na zniszczenie)" },
      { version: "0.19.0", title: "Modifier: Borderland Syncretism", status: "planned", phase: "territory", items: ["Harmony zamiast Descent na pograniczu"] },
      { version: "0.20.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~6 eventow", "1 decyzja", "~6 modifierow"] },
      { version: "1.1.0", title: "Decyzja: Korytarz Wolchwow", status: "post", phase: "post-release", items: ["Strefa buforowa dla uchodzcow"] },
      { version: "1.2.0", title: "Event: Wyslannicy z Rzymu i Konstantynopola", status: "post", phase: "post-release", items: ["Intryguj jednych przeciw drugim"] },
      { version: "1.3.0", title: "Modifier: Western Gate", status: "post", phase: "post-release", items: ["+1 wolchw network level"] },
      { version: "1.4.0", title: "Ending: Laboratorium Synkretyzmu", status: "post", phase: "post-release", items: ["Pogranicze jako trwaly bufor wiary"] },
    ],
    decisions: [
      { topic: "Dual Frontier", decision: "Passive auto", reason: "Automatyczny modifier — geography is mechanic" },
      { topic: "Tatarski Chaos", decision: "On_action", reason: "Reaguje na zniszczenie — bardziej dynamiczne" },
    ],
  },

  /* ───── Moldavia ───── */
  "semd_": {
    preReleaseCount: 12,
    postReleaseCount: 4,
    releaseStats: { events: 6, decisions: 2, buildings: 0, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix"] },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "semd_is_moldavia", "semd_is_tivertsi", "localization"] },
      { version: "0.12.0", title: "Modyfikatory", status: "planned", phase: "foundation", items: ["semd_river_shrines", "semd_steppe_pact", "semd_peripheral_survival"] },
      { version: "0.13.0", title: "Decyzja: Pakt Stepowy", status: "planned", phase: "narrative", items: ["Sojusz z Pieczyngami/Kumanami", "bonus militarny", "timer 30 lat"], decision: "Decyzja + timer (30 lat)" },
      { version: "0.14.0", title: "Modifier: Rzeki jako Swiatynie", status: "planned", phase: "narrative", items: ["Brak stalych swiatyn", "-25% Fervor stability"] },
      { version: "0.15.0", title: "Event: Pieczyngowie Pytaja o Boga", status: "planned", phase: "narrative", items: ["Wymiana rytualow", "synkretyzm/separacja"] },
      { version: "0.16.0", title: "Modifier: Przetrwanie przez Peryferynosc", status: "planned", phase: "narrative", items: ["Descent skalowany do odleglosci od metropolii"] },
      { version: "0.17.0", title: "Decyzja: Brodnickie Bractwo", status: "planned", phase: "rivalry", items: ["Proto-Kozacy", "bonus militarny", "niewidzialny dla misjonarzy"] },
      { version: "0.18.0", title: "Event: Tatarzy Nie Widza Nas (1240)", status: "planned", phase: "rivalry", items: ["Brak miast = brak celow", "anonimowosc"] },
      { version: "0.19.0", title: "Modifier: Rzeka Obronna", status: "planned", phase: "territory", items: ["Dniestr/Prut jako linia obrony", "+fort_level"] },
      { version: "0.20.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "steppe pact balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~6 eventow", "2 decyzje", "~6 modifierow"] },
      { version: "1.1.0", title: "Budynek: Grod nad Dniestrem", status: "post", phase: "post-release", items: ["Umocnienie rzeczne", "+fort_level"] },
      { version: "1.2.0", title: "Event chain: Tivertsi Exodus", status: "post", phase: "post-release", items: ["Migracja plemienna"] },
      { version: "1.3.0", title: "Modifier: Synkretyzm Stepowy", status: "post", phase: "post-release", items: ["Perun/Tengri hybrid po 50 lat Paktu"], decision: "Post-release (zlozonosc)" },
      { version: "1.4.0", title: "Ending: Niewidzialne Krolestwo", status: "post", phase: "post-release", items: ["Peryferyjna przetrwalosc 150 lat"] },
    ],
    decisions: [
      { topic: "Pakt Stepowy", decision: "Decyzja + timer (30 lat)", reason: "Proste, przewidywalne; gracz aktywuje i odnawia" },
      { topic: "Synkretyzm Stepowy", decision: "Post-release", reason: "Hybryd Perun/Tengri — po stabilizacji core" },
    ],
  },

  /* ───── Polotsk ───── */
  "sept_": {
    preReleaseCount: 14,
    postReleaseCount: 4,
    releaseStats: { events: 8, decisions: 2, buildings: 0, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix"] },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "sept_is_polotsk", "sept_is_polochans", "localization"] },
      { version: "0.12.0", title: "Trait: Wilcza Krew", status: "planned", phase: "foundation", items: ["sept_trait_wolf_blood", "+3 prowess", "-0.1 piety", "+5 dread", "+20% conversion resistance"], decision: "Dziedziczenie 50% (organiczne)" },
      { version: "0.13.0", title: "Modifier: Cien Rognedy", status: "planned", phase: "foundation", items: ["-15 opinion Rurikids", "+10 lokalni", "+5 Fervor"] },
      { version: "0.14.0", title: "Event: Nocna Przemiana", status: "planned", phase: "narrative", items: ["Co 12 lat dla wolf_blood", "opcje: przyjmij/opieraj sie", "+2 prowess 10 lat"] },
      { version: "0.15.0", title: "Decyzja: Rytual Krwi Wilka", status: "planned", phase: "narrative", items: ["Rogvolodovichi + c_polotsk + 200 piety", "nadaje wolf_blood"] },
      { version: "0.16.0", title: "Event: Kosciol zada egzorcyzmu", status: "planned", phase: "narrative", items: ["Biskup odkrywa wolf_blood", "3 opcje: przyjmij/wygon/udaj"] },
      { version: "0.17.0", title: "Event: Wsielsaw na Tronie Kijowskim (1068)", status: "planned", phase: "narrative", items: ["ALT: zostac w Kijowie lub wrocic", "flavor z modifierem"], decision: "Flavor only (vanilla dates nietykane)" },
      { version: "0.18.0", title: "Event: Kupiec od Nowogrodu", status: "planned", phase: "rivalry", items: ["Link Polotsk-Novgorod", "szlak wareski modifier"] },
      { version: "0.19.0", title: "Modifier: Wilcza Krew na Tronie", status: "planned", phase: "rivalry", items: ["wolf_blood + poganski Polotsk", "+20% resistance"] },
      { version: "0.20.0", title: "Decyzja: Kult Wilka", status: "planned", phase: "rivalry", items: ["Formalizacja kultu szamanskiego", "Weles jako pan wilkow"] },
      { version: "0.21.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "wolf_blood balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~8 eventow", "2 decyzje", "~6 modifierow", "1 trait"] },
      { version: "1.1.0", title: "Modifier: Pamiec Rognedy", status: "post", phase: "post-release", items: ["Dynastyczny", "-relations Rurikids", "slabnie per pokolenie"] },
      { version: "1.2.0", title: "Event: Eufrozyna chce klasztoru", status: "post", phase: "post-release", items: ["XII w.", "opcje: pozwol/wydaj za maz/wyslij do swietnicy"], decision: "Post-release" },
      { version: "1.3.0", title: "Budynek: Wlocznia Wsielawa", status: "post", phase: "post-release", items: ["c_polotsk", "+prowess", "+dread"] },
      { version: "1.4.0", title: "Ending: Krolestwo Wilka", status: "post", phase: "post-release", items: ["Poganski Polotsk do XIII w.", "sojusz z Baltami"] },
    ],
    decisions: [
      { topic: "Wilcza Krew dziedziczenie", decision: "50% szansy", reason: "Organiczne — dziecko holdera ma szanse odziedziczyc" },
      { topic: "Wsielsaw w Kijowie", decision: "Flavor only", reason: "Vanilla daty nietykane; event narratywny z modifierem" },
      { topic: "Eufrozyna", decision: "Post-release", reason: "Wolf blood + Rogneda to wystarczajacy rdzen 1.0.0" },
    ],
  },

  /* ───── Opolye ───── */
  "seop_": {
    preReleaseCount: 12,
    postReleaseCount: 4,
    releaseStats: { events: 6, decisions: 1, buildings: 0, modifiers: 6 },
    versions: [
      { version: "0.1–0.9", title: "Istniejaca zawartosc", status: "done", phase: "foundation", items: ["Brak zawartosci — scaffold czysty"] },
      { version: "0.10.0", title: "SSP Decoupling", status: "planned", phase: "foundation", items: ["has_mod guardy", "descriptor fix"] },
      { version: "0.11.0", title: "Scaffold", status: "planned", phase: "foundation", items: ["descriptor.mod", "seop_is_opolye", "seop_is_vyatichi", "localization"] },
      { version: "0.12.0", title: "Modifier: Lasy Oki", status: "planned", phase: "foundation", items: ["+30% conversion resistance", "-20% development", "+10% levy"] },
      { version: "0.13.0", title: "Event: Zebranie Opola", status: "planned", phase: "narrative", items: ["Co 10 lat: Prawa Ojcow / Wymiana / Wiec nowy lider"], decision: "Wiec moze zmienic wladce" },
      { version: "0.14.0", title: "Decyzja: Lesne Sanktuaria", status: "planned", phase: "narrative", items: ["Ukryte miejsca kultu", "+conversion resistance", "-development 30 lat"] },
      { version: "0.15.0", title: "Modifier: Wiatycka Pamiec", status: "planned", phase: "narrative", items: ["Dynastyczny", "+5 opinion", "+3 Fervor", "2 pokolenia"] },
      { version: "0.16.0", title: "Event: Wolchw z Bialej Rusi", status: "planned", phase: "narrative", items: ["Cross-link sewr_", "co 20 lat", "opcje: przyjmij/odrzuc"], decision: "Pre-release (pierwszy cross-kingdom event)" },
      { version: "0.17.0", title: "Event: Wiec Odrzuca Chrzest", status: "planned", phase: "rivalry", items: ["Zgromadzenie glosuje przeciw", "+Fervor"] },
      { version: "0.18.0", title: "Event: Mnich Kukusza (1113)", status: "planned", phase: "rivalry", items: ["ALT: opole legalnie wydalaja mnicha", "brak meczennika"] },
      { version: "0.19.0", title: "Modifier: Bagna Oki", status: "planned", phase: "territory", items: ["Terrain", "-50% invasion efficiency"] },
      { version: "0.20.0", title: "QA + Balans", status: "planned", phase: "qa", items: ["testy", "opole balans", "loc audit"] },
      { version: "1.0.0", title: "RELEASE", status: "planned", phase: "release", items: ["~6 eventow", "1 decyzja", "~6 modifierow"] },
      { version: "1.1.0", title: "Decyzja: Kodyfikacja Prawa Opolnego", status: "post", phase: "post-release", items: ["Formalizacja prawa zgromadzenia"] },
      { version: "1.2.0", title: "Event: Tatarzy Omijaja Opolye (1237)", status: "post", phase: "post-release", items: ["Suzdale pada; Opolye za bagnami"] },
      { version: "1.3.0", title: "Cross-mod: Ruthenia Vyatichi arc", status: "post", phase: "post-release", items: ["Hook na sekr_ wspolna kultura"] },
      { version: "1.4.0", title: "Ending: Wiatycka Wytrwalosc", status: "post", phase: "post-release", items: ["Opor 200 lat", "permanentny modifier"] },
    ],
    decisions: [
      { topic: "Zebranie Opola", decision: "Zmiana wladcy mozliwa", reason: "Rewolucyjna mechanika — duze stakes" },
      { topic: "Cross-event sewr", decision: "Pre-release", reason: "Pierwszy cross-kingdom event — precedens w 1.0.0" },
    ],
  },
};
